### ISSUE TITLE
Generate CNAME from build script

### ISSUE THREAD

**Issue by bossiernesto** [uqbar-project/wiki#4]
This is to prevent an issue with a fork of this project that may cause the CNAME for the gh-pages build not actually work properly. 

A solution might be to generate this CNAME from the build process.

**Comment by bossiernesto** [comment]
possible fix on d12b265

**Comment by PalumboN** [comment]
:clap:

**Comment by bossiernesto** [comment]
I've managed to update the Rakefile and now the CNAME is being generated on the fly. Let me know if it's working.

**Comment by bossiernesto** [comment]
This improvement was solved in d12b265. Closing ticket. If any issue related with CNAME appears, open a new ticket please.
