### ISSUE TITLE
Links caídos

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wiki#5]
La mayoría de los links que aparecen en el artículo de [robustez de los lenguajes](http://wiki.uqbar.org/wiki/articles/robustez-de-los-lenguajes.html) están caídos :(

**Comment by bossiernesto** [comment]
Voy a agregar un feature para que notifique los links caidos en todos los articulos, voy a ver si puedo crear notificaciones por circleci y usar html-proofer. Al menos esto si bien no soluciona el problema, nos va a avisar sobre que links hay que actualizar

**Comment by PalumboN** [comment]
!!! Usted es muy groso Sr. Bossi

**Comment by bossiernesto** [comment]
Ya existe un cambio que permite generar un artefacto por cada build de ci y que muestra los links en los que hay problemas. Estos links son externos, en caso de que sean internos habría que arreglar el md o html correspondiente. El link para ver el archivo con los links que estan fallando se puede ver en 

https://circleci.com/api/v1/project/uqbar-project/wiki/60/artifacts/0/$CIRCLE_ARTIFACTS/failed_urls.txt

Este link pertenece al build nro. 60, y en caso de que se desee ver el artifact de los urls que fallan, basta con cambiar el nro de build por el último, por lo que el link

https://circleci.com/api/v1/project/uqbar-project/wiki/<build_id>/artifacts/0/$CIRCLE_ARTIFACTS/failed_urls.txt

hay que reemplazar build_id por el ultimo build actual sobre el branch master.

En el proximo commit, dejare un hook que funcionara en el watch de jekyll, cuando se quiera hacer un cambio con una instancia local de jekyll. Y que verificará los links externos sobre un archivo que se haya modificado localmente desde que se haya levantado la instancia de jekyll.

**Comment by bossiernesto** [comment]
En #9 se agrego el hook. Ahora se tiene tanto los artefactos por build como una manera de verlo cuando se levanta un jekyll localmente.

**Comment by bossiernesto** [comment]
Para los links caidos, se puede buscar para atras el contenido en archive.org o bien el de ver un link alternativo o actualizado. Ya fixee algunos en 0d475d7. El resto esta descripto en el artifact https://74-80790096-gh.circle-artifacts.com/0/tmp/circle-artifacts.fzqNuL6/failed_urls.txt

Actualizo...

En 0d468c4 y 0d475d7 fixee la mayoría de los links rotos.

https://74-80790096-gh.circle-artifacts.com/0/tmp/circle-artifacts.fzqNuL6/failed_urls.txt

muestra la lista de links rotos antes de estos dos commits, luego de estos commits, los links "rotos" son 

https://76-80790096-gh.circle-artifacts.com/0/tmp/circle-artifacts.EqvM9zU/failed_urls.txt

**Comment by fdodino** [comment]
Cierro issue ya que se arreglaron los links caídos
